### ISSUE TITLE
The provisioner 'ansible' doesn't exist.

### ISSUE THREAD

**Issue by gcatlin** [dsander/vagrant-ansible#4]
I followed the README.md instructions and received the following error after entering `vagrant up`:

```
There was a problem with the configuration of Vagrant. The error message(s)
are printed below:

vm:
* The provisioner 'ansible' doesn't exist.
```

My Vagrant file:

```
Vagrant::Config.run do |config|
  config.vm.box     = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.customize ["modifyvm", :id, "--memory", "512"]
  config.vm.customize ["modifyvm", :id, "--cpus", "1"]

  config.vm.provision :ansible do |ansible|
    # point Vagrant at the location of your playbook you want to run
    ansible.playbook = "nginx-ubuntu.yml"

    # the Vagrant VM will be put in this host group change this should
    # match the host group in your playbook you want to test
    ansible.hosts = "web-servers"
  end
end
```

`gem list | grep vagrant`

```
vagrant (1.0.3)
vagrant-ansible (0.0.3)
```

Some one else had this issue recently: https://groups.google.com/forum/#!msg/vagrant-up/eVlQ_0IUPv8/pJAnCK-OlYgJ

Any idea what may be going on?

**Comment by dsander** [comment]
The sample Vagrantfile I provided was missing the 

```
require 'vagrant-ansible'
```

line to load the ansible plugin. Just add the line at the top and you should be fine.

**Comment by gcatlin** [comment]
@dsander, thanks. I made that change, then received a new error:

```
$ vagrant status
/Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- vagrant-ansible (LoadError)
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/xxxxxxxx/yyyyyy/ansible-playbooks/Vagrantfile:2:in `<top (required)>'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:115:in `load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:115:in `block in procs_for_source'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/config.rb:41:in `block in capture_configures'
    from <internal:prelude>:10:in `synchronize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/config.rb:36:in `capture_configures'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:114:in `procs_for_source'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:51:in `block in set'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:45:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:45:in `set'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/environment.rb:377:in `block in load_config!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in `load_config!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/environment.rb:327:in `load!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.3/bin/vagrant:40:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:19:in `load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:19:in `<main>'
```

I'm not an expert on Ruby gems or Vagrant, but it seems as though Vagrant prefers to manage its own gem sets. I had to install `vagrant-ansible` this way to get it working:

```
vagrant gem install vagrant-ansible
```

I recommend updating the README.md to reflect this.

Would you like me to make the change and submit a pull request?

**Comment by dsander** [comment]
Interesting looks like an issue related to the vagrant installation on OSX. Did you install vagrant via rubygems or used a separate package?

A pull request with an updated README would be great

**Comment by gcatlin** [comment]
I installed Vagrant using `Vagrant-1.0.3.dmg` from http://downloads.vagrantup.com/tags/v1.0.3

Also, I'm running `ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0]` installed via Homebrew. I am _not_ using any ruby version or gemset tools like rvm, rbenv, etc.

**Comment by dsander** [comment]
Thanks for the info, I updated the README for vagrant package users.

**Comment by sblask** [comment]
```
vagrant gem install vagrant-ansible
```

would fail for me with a LoadError as well if executed in a directory that contains a Vagrantfile. Other directories worked fine, but only after I installed the ruby dev package (I installed Vagrant using apt-get under Ubuntu). Maybe these requirements would be woth mentioning in the README as well?

**Comment by andrewcstewart** [comment]
I'm having a similar issue with a custom provisioner.  I think this might be the issue: http://stackoverflow.com/questions/9154365/ruby-loaderror-cannot-load-such-file
