### ISSUE TITLE
When using extra-vars in ansible.options only the first variable is read

### ISSUE THREAD

**Issue by TizianoPerrucci** [dsander/vagrant-ansible#6]
For instance if I configure
ansible.options = '--extra-vars="user=vagrant test=true"', '-vv'

only the variable 'user' will be visible in the playbook, the 'test' variable is lost

**Comment by jure** [comment]
The same is happening to me.

**Comment by dsander** [comment]
I tried to reproduce this issue, but the called command looks right to me.
https://github.com/dsander/vagrant-ansible/blob/master/spec/vagrant-ansible/provisioner_spec.rb#L83-L96

**Comment by jure** [comment]
Yes, I take it back, I was doing something stupid (non-escaped new lines for multiple-line shell command). Sorry.

**Comment by mbadran** [comment]
This is also happening for me. Are you sure the test is still passing? My syntax looks the same, and it's not working.

This in vagrant-ansible:

```
ansible.options  = '--extra-vars="user=vagrant test=true"', '-vv'
```

With this debug module:

```
- name: temp test of included vars
  debug: msg="user = ${user}"
```

Results in this output:

```
TASK: [temp test of included vars] ********************* 
ok: [10.30.11.10] => {"item": "", "msg": "user = vagrant test=true"}
```

The first extra var, 'user', is slurping the value of the other vars.

I'm running this with the latest version of ansible (1.1 devel 36f613f51e) and the latest vagrant-ansible code. I tried both bash and zsh (on OS X Mountain Lion), if that makes any difference.

**Comment by mbadran** [comment]
I think this had to do with the quotes used.

In any case, here's a better way to do extra-vars: https://github.com/dsander/vagrant-ansible/pull/16

**Comment by stelcheck** [comment]
This still happens to me with 1.3.5, using hashes. I can get around this at this time, but it's kind of annoying... 

Maybe this has been fixed already in the repo?
