### ISSUE TITLE
Permission denied (publickey,password) with a brand-new box

### ISSUE THREAD

**Issue by yeukhon** [dsander/vagrant-ansible#7]
``` bash
$ vagrant provision
[default] Running provisioner: Vagrant::Provisioners::Ansible...
ansible-playbook
--user=vagrant
--inventory-file=/tmp/inventory20130105-10967-w9tt4p
--private-key=/home/glasslab/.vagrant.d/insecure_private_key
nginx-ubuntu.yml

PLAY [web-servers] ********************* 

GATHERING FACTS ********************* 
fatal: [127.0.0.1] => failed to transfer file to /setup:

Permission denied (publickey,password).
Couldn't read packet: Connection reset by peer


TASK: [install python-software-properties] ********************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************* 
127.0.0.1                      : ok=0    changed=0    unreachable=1    failed=0 
```

I am using Vangrant's precise 32 box. 
I am not saying I don't trust your box, but I am supposed to use precise.
What else did you put in your box that didn't exist in a fresh box?

Thanks.

**Comment by yeukhon** [comment]
Actually, I get the same error when using your box. Any idea what's going on? Thanks.

**Comment by lorin** [comment]
Looks like ssh is failing. Can you post the output if you try to manually ssh to the instance the same way vagrant is trying:

```
ssh -l vagrant -i /home/glasslab/.vagrant.d/insecure_private_key 127.0.0.1 -p 2222
```

(I'm assuming here that vagrant is using its default of 2222 for ssh of the VM)

**Comment by yeukhon** [comment]
``` bash
ssh -l vagrant -i /home/glasslab/.vagrant.d/insecure_private_key 127.0.0.1 -p 2222
Welcome to Ubuntu 11.10 (GNU/Linux 3.0.0-12-generic i686)

 * Documentation:  https://help.ubuntu.com/
New release '12.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Thu Apr 19 01:45:38 2012
vagrant@nettuno:~$ 
```

Hi, lorin
Thanks. I can login using that command no problem as seen above.

**Comment by lorin** [comment]
@yeukhon Can you post your ansible playbook and your Vagrantfile?

**Comment by yeukhon** [comment]
@lorin  I use the quickstart playbook suggested in the README. 
I modified the memory to 400. That's all I did.

**Comment by lorin** [comment]
@yeukhon Sanity check: can you confirm that the nginx-ubuntu.yml file uses the vagrant user instead of the ubuntu user:

```
user: vagrant
```

**Comment by yeukhon** [comment]
No. It uses ubuntu user. I see `--user=vagrant` is passed when starting vagrant.

**Comment by yeukhon** [comment]
and according to `cat /etc/passwd` there is no ubuntu. I should try using vagrant, right? I can try that now.

**Comment by lorin** [comment]
Yes, you should use the vagrant user. This is documented in the vagrant-ansible README, but it's an easy step to miss.

**Comment by yeukhon** [comment]
Thank you @lorin 
I have to modify other stuff in cookbook as well. 
I will create a pull request in a few days.

Thank you so much!
