### ISSUE TITLE
No such file or directory ansible-playbook

### ISSUE THREAD

**Issue by hutchic** [dsander/vagrant-ansible#9]
In all likelihood this is because I've messed up while installing or configuring but whenever I try and run a ansible cook book I get the error 

safe_exec.rb:23:in `exec': No such file or directory - ansible-playbook (Errno::ENOENT)

Full stack trace available here: https://gist.github.com/4566559

**Comment by steverice** [comment]
I was having this issue too. You probably just need to install ansible on your host machine.

**Comment by hutchic** [comment]
ok that fixed it thanks for the suggestion
